import { FoodItem } from "../types";

export const mockFoodItems: FoodItem[] = [
  {
    id: "1",
    name: "Vegge Lover",
    description: "Extra-virgin olive oil, garlic, mozzarella cheese, onions, mushrooms, green olives, black olives",
    price: 14.90,
    image: "https://ext.same-assets.com/868996137/3829143959.png",
    category: "pizza",
    rating: 4.0,
    isPopular: true,
  },
  {
    id: "2",
    name: "Pepperoni Calzone",
    description: "Piled with shrimp, calamari, clams, mussels, surimi and stretchy mozzarella, seasoned with tangy lemon pepper.",
    price: 15.80,
    discountedPrice: 12.00,
    image: "https://ext.same-assets.com/868996137/3777996267.png",
    category: "pizza",
    rating: 4.0,
    isPopular: true,
    isSale: true,
  },
  {
    id: "3",
    name: "Apricot Chicken",
    description: "Crispy bacon, tasty ham, pineapple, onion and stretchy mozzarella, finished with a BBQ swirl.",
    price: 18.30,
    image: "https://ext.same-assets.com/868996137/3535270907.png",
    category: "pizza",
    rating: 3.6,
    isPopular: true,
  },
  {
    id: "4",
    name: "Plain Tea",
    description: "Iced coffee is a type of coffee beverage served chilled, brewed variously with the fundamental",
    price: 18.31,
    image: "https://ext.same-assets.com/868996137/2607069850.png",
    category: "hotDrink",
    rating: 4.0,
    isPopular: true,
  },
  {
    id: "5",
    name: "Penne Funghi Chicken",
    description: "A mighty meaty double helping of all the reasons you love our burger.",
    price: 14.40,
    image: "https://ext.same-assets.com/868996137/2687625510.png",
    category: "pasta",
    rating: 3.5,
    isPopular: true,
  },
  {
    id: "6",
    name: "Bacon Burger",
    description: "A mighty meaty double helping of all the reasons you love our burger.",
    price: 10.95,
    image: "https://ext.same-assets.com/868996137/4292183539.png",
    category: "burger",
    rating: 4.0,
    isPopular: true,
  },
  {
    id: "7",
    name: "Trio Cafe",
    description: "Trio Cafe is Family owned establishment located in Boston Waterfront next to World Trade Center.",
    price: 12.18,
    image: "https://ext.same-assets.com/868996137/3798927303.png",
    category: "coldDrink",
    rating: 4.2,
    isPopular: true,
  },
  {
    id: "8",
    name: "Black Coffee",
    description: "Browse unique Coca-Cola products, clothing, & accessories, or customize Coke bottles and gifts",
    price: 11.76,
    image: "https://ext.same-assets.com/868996137/3301836042.png",
    category: "hotDrink",
    rating: 4.0,
    isPopular: true,
  },
  {
    id: "9",
    name: "Trio Cheese",
    description: "Mouth watering pepperoni, cabanossi, mushroom, capsicum, black olives and stretchy mozzarella.",
    price: 16.93,
    image: "https://ext.same-assets.com/868996137/3777996267.png",
    category: "pizza",
    rating: 3.8
  },
  {
    id: "10",
    name: "Summer Pizza",
    description: "Shrimp, Red Capsicum, Green Capsicum, Onion, Chilli flakes, Lemon Pepper, Mozzarella, finished with Aioli",
    price: 12.15,
    discountedPrice: 9.00,
    image: "https://ext.same-assets.com/868996137/3829143959.png",
    category: "pizza",
    rating: 4.0,
    isSale: true
  },
  {
    id: "11",
    name: "Supreme Pizza",
    description: "Ricotta, sun dried tomatoes, garlic, mozzarella cheese, topped with lightly drizzled red sauce, pesto, and",
    price: 11.75,
    discountedPrice: 6.00,
    image: "https://ext.same-assets.com/868996137/3535270907.png",
    category: "pizza",
    rating: 4.6,
    isSale: true
  },
  {
    id: "12",
    name: "Tagliatelle Molto",
    description: "A mighty meaty double helping of all the reasons you love our pasta.",
    price: 15.61,
    image: "https://ext.same-assets.com/868996137/2687625510.png",
    category: "pasta",
    rating: 4.6
  }
];
